# Generated by Django 3.2.25 on 2025-05-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bathrooms", models.FloatField()),
                ("bedrooms", models.IntegerField()),
                ("home_size", models.IntegerField()),
                ("home_type", models.TextField()),
                ("last_sold_date", models.DateTimeField(blank=True, null=True)),
                ("last_sold_price", models.IntegerField()),
                ("link", models.TextField()),
                ("price", models.IntegerField()),
                ("property_size", models.IntegerField()),
                ("rent_price", models.IntegerField()),
                ("rentzestimate_amount", models.IntegerField()),
                (
                    "rentzestimate_last_updated",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("tax_value", models.IntegerField()),
                ("tax_year", models.IntegerField()),
                ("year_built", models.IntegerField()),
                ("zestimate_amount", models.IntegerField()),
                ("zestimate_last_updated", models.DateTimeField(blank=True, null=True)),
                ("zillow_id", models.TextField()),
                ("address", models.TextField()),
                ("city", models.TextField()),
                ("state", models.TextField()),
                ("zipcode", models.TextField()),
            ],
            options={
                "db_table": "listings",
            },
        ),
        migrations.AddConstraint(
            model_name="listings",
            constraint=models.UniqueConstraint(
                fields=("zillow_id",), name="unique_zillow_id"
            ),
        ),
    ]
